Model_Index: 41
TreatmentTarget: G2M
batch_number: 3
num_batches: 10
num_worker: 16
Total_sample_limit: 500
T: 200
load_history_flag: true
history_folder:  prior_simulation_identifiability_batch2Model41_2025_05_13_23_31
para_label : '"$q_1$","$q_2$","$q_3$","$q_4$","$m_{d,FR}^{max}$","$m_{d,UR}^{max}$","$m_{d,MS}^{max}$","$m_{d,UR,G1}^{max}$","$m_{d,UR,S}^{max}$","$\tilde{\lambda}_{d,max,G1}$","$\tilde{\lambda}_{G2arrest,UR, max}$","$\tilde{\lambda}_{G2arrest,FR, max}$","$\tilde{\lambda}_{G2arrest,MS, max}$","$\tilde{\lambda}_{G1arrest, max}$","$\tilde{\lambda}_{d,max,S}$","$\tilde{\lambda}_{Sarrest, max}$","$\tilde{b}$","$\tilde{b}_d$","$n_{G2M}$","$EC_{50,d}$","$EC_{50}$","$a_S$","$b_S$","$\theta_1$","$\theta_2$","$\theta_3$"'
para_exclude: '"$n_{G2M}$","$EC_{50,d}$","$EC_{50}$"'
